[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -m gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --worker-class sync 'data_formulator.app:app'"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
